// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/nowhere/config.proto

package nowhere

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Certificate is a PEM encoded TLS certificate and private key.
type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_proxy_nowhere_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_nowhere_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_proxy_nowhere_config_proto_rawDescGZIP(), []int{0}
}

func (x *Certificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *Certificate) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// Endpoint is one Nowhere peer. up and down are tcp, udp, or mix.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Up            string                 `protobuf:"bytes,4,opt,name=up,proto3" json:"up,omitempty"`
	Down          string                 `protobuf:"bytes,5,opt,name=down,proto3" json:"down,omitempty"`
	Mux           bool                   `protobuf:"varint,6,opt,name=mux,proto3" json:"mux,omitempty"`
	Morph         bool                   `protobuf:"varint,7,opt,name=morph,proto3" json:"morph,omitempty"`
	ServerName    string                 `protobuf:"bytes,8,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Pin           string                 `protobuf:"bytes,9,opt,name=pin,proto3" json:"pin,omitempty"`
	AllowInsecure bool                   `protobuf:"varint,10,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	Pool          int32                  `protobuf:"varint,11,opt,name=pool,proto3" json:"pool,omitempty"`
	Alpn          string                 `protobuf:"bytes,12,opt,name=alpn,proto3" json:"alpn,omitempty"`
	MixFallbackNs int64                  `protobuf:"varint,13,opt,name=mix_fallback_ns,json=mixFallbackNs,proto3" json:"mix_fallback_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_proxy_nowhere_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_nowhere_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_proxy_nowhere_config_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Endpoint) GetUp() string {
	if x != nil {
		return x.Up
	}
	return ""
}

func (x *Endpoint) GetDown() string {
	if x != nil {
		return x.Down
	}
	return ""
}

func (x *Endpoint) GetMux() bool {
	if x != nil {
		return x.Mux
	}
	return false
}

func (x *Endpoint) GetMorph() bool {
	if x != nil {
		return x.Morph
	}
	return false
}

func (x *Endpoint) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Endpoint) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Endpoint) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *Endpoint) GetPool() int32 {
	if x != nil {
		return x.Pool
	}
	return 0
}

func (x *Endpoint) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *Endpoint) GetMixFallbackNs() int64 {
	if x != nil {
		return x.MixFallbackNs
	}
	return 0
}

type ServerConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Password string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Empty enables both tcp and udp.
	Networks     []string       `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`
	Morph        bool           `protobuf:"varint,3,opt,name=morph,proto3" json:"morph,omitempty"`
	Certificates []*Certificate `protobuf:"bytes,4,rep,name=certificates,proto3" json:"certificates,omitempty"`
	Alpn         string         `protobuf:"bytes,5,opt,name=alpn,proto3" json:"alpn,omitempty"`
	// Next forwards flows to another Nowhere portal instead of the router.
	Next          *Endpoint `protobuf:"bytes,6,opt,name=next,proto3" json:"next,omitempty"`
	UserLevel     uint32    `protobuf:"varint,7,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_nowhere_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_nowhere_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_nowhere_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ServerConfig) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ServerConfig) GetMorph() bool {
	if x != nil {
		return x.Morph
	}
	return false
}

func (x *ServerConfig) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *ServerConfig) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *ServerConfig) GetNext() *Endpoint {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *ServerConfig) GetUserLevel() uint32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

type ClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	UserLevel     uint32                 `protobuf:"varint,2,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_nowhere_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_nowhere_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_nowhere_config_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConfig) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ClientConfig) GetUserLevel() uint32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

var File_proxy_nowhere_config_proto protoreflect.FileDescriptor

const file_proxy_nowhere_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/nowhere/config.proto\x12\x12xray.proxy.nowhere\"A\n" +
	"\vCertificate\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\xca\x02\n" +
	"\bEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02up\x18\x04 \x01(\tR\x02up\x12\x12\n" +
	"\x04down\x18\x05 \x01(\tR\x04down\x12\x10\n" +
	"\x03mux\x18\x06 \x01(\bR\x03mux\x12\x14\n" +
	"\x05morph\x18\a \x01(\bR\x05morph\x12\x1f\n" +
	"\vserver_name\x18\b \x01(\tR\n" +
	"serverName\x12\x10\n" +
	"\x03pin\x18\t \x01(\tR\x03pin\x12%\n" +
	"\x0eallow_insecure\x18\n" +
	" \x01(\bR\rallowInsecure\x12\x12\n" +
	"\x04pool\x18\v \x01(\x05R\x04pool\x12\x12\n" +
	"\x04alpn\x18\f \x01(\tR\x04alpn\x12&\n" +
	"\x0fmix_fallback_ns\x18\r \x01(\x03R\rmixFallbackNs\"\x86\x02\n" +
	"\fServerConfig\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnetworks\x18\x02 \x03(\tR\bnetworks\x12\x14\n" +
	"\x05morph\x18\x03 \x01(\bR\x05morph\x12C\n" +
	"\fcertificates\x18\x04 \x03(\v2\x1f.xray.proxy.nowhere.CertificateR\fcertificates\x12\x12\n" +
	"\x04alpn\x18\x05 \x01(\tR\x04alpn\x120\n" +
	"\x04next\x18\x06 \x01(\v2\x1c.xray.proxy.nowhere.EndpointR\x04next\x12\x1d\n" +
	"\n" +
	"user_level\x18\a \x01(\rR\tuserLevel\"g\n" +
	"\fClientConfig\x128\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1c.xray.proxy.nowhere.EndpointR\bendpoint\x12\x1d\n" +
	"\n" +
	"user_level\x18\x02 \x01(\rR\tuserLevelBX\n" +
	"\x16com.xray.proxy.nowhereP\x01Z'github.com/xtls/xray-core/proxy/nowhere\xaa\x02\x12Xray.Proxy.Nowhereb\x06proto3"

var (
	file_proxy_nowhere_config_proto_rawDescOnce sync.Once
	file_proxy_nowhere_config_proto_rawDescData []byte
)

func file_proxy_nowhere_config_proto_rawDescGZIP() []byte {
	file_proxy_nowhere_config_proto_rawDescOnce.Do(func() {
		file_proxy_nowhere_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_nowhere_config_proto_rawDesc), len(file_proxy_nowhere_config_proto_rawDesc)))
	})
	return file_proxy_nowhere_config_proto_rawDescData
}

var file_proxy_nowhere_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_nowhere_config_proto_goTypes = []any{
	(*Certificate)(nil),  // 0: xray.proxy.nowhere.Certificate
	(*Endpoint)(nil),     // 1: xray.proxy.nowhere.Endpoint
	(*ServerConfig)(nil), // 2: xray.proxy.nowhere.ServerConfig
	(*ClientConfig)(nil), // 3: xray.proxy.nowhere.ClientConfig
}
var file_proxy_nowhere_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.nowhere.ServerConfig.certificates:type_name -> xray.proxy.nowhere.Certificate
	1, // 1: xray.proxy.nowhere.ServerConfig.next:type_name -> xray.proxy.nowhere.Endpoint
	1, // 2: xray.proxy.nowhere.ClientConfig.endpoint:type_name -> xray.proxy.nowhere.Endpoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_nowhere_config_proto_init() }
func file_proxy_nowhere_config_proto_init() {
	if File_proxy_nowhere_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_nowhere_config_proto_rawDesc), len(file_proxy_nowhere_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_nowhere_config_proto_goTypes,
		DependencyIndexes: file_proxy_nowhere_config_proto_depIdxs,
		MessageInfos:      file_proxy_nowhere_config_proto_msgTypes,
	}.Build()
	File_proxy_nowhere_config_proto = out.File
	file_proxy_nowhere_config_proto_goTypes = nil
	file_proxy_nowhere_config_proto_depIdxs = nil
}
